apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-g3i3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-g3i3
    app.kubernetes.io/part-of: ci1t-830-0096-app
  name: devfile-sample-g3i3
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-g3i3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-g3i3
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0096-tenant/ci1t-830-0096-app/devfile-sample-g3i3@sha256:4cc9454b788e69d177f13d50d1806f1d30e6342345dd38669b579a5f5fdfe17c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
